### PR TITLE
Fix for #60 : Scrumbler Javascripts not working with SSL

### PR DESCRIPTION
**Pull request by letic**
Here is a propose fix for this issue.

Beware it won't work for people using redmine in a sub-url (ie
http://mydomain.com/redmine/)

### CODE REVIEW

**Comment by zloydadka** [comment]
this code dont needed
solution is: correct front-end server headers configuration
for nginx: proxy_set_header X-Forwarded-Proto https;
for apache: RequestHeader set X_FORWARDED_PROTO 'https'

**Comment by letic** [comment]
Hey zloydadka,

Thanks for the answer, but as I said in #60 I am using Nginx with phusion passenger. There is no proxying involved. 

I already tried the solution proposed before opening the ticket, without any change of behaviour.

Maybe it is a bug in nginx and/or phusion passenger...

**Comment by zloydadka** [comment]
oh man
i'm not developer of passenger, but i read it's documentation if i use it.

your solution is:
passenger_set_cgi_param HTTP_X_FORWARDED_PROTO https;

**Comment by zloydadka** [comment]
http://www.modrails.com/documentation/Users%20guide%20Nginx.html#_passenger_set_cgi_param_lt_cgi_environment_name_gt_lt_value_gt

**Comment by letic** [comment]
Yep I was looking at it after my last comment realising that it might be an issue in nginx/passenger, and found that same options. But you beat me to the reply :)

Thanks for your help !
Keep up the good work.

**Pull request closed without merging**
