### PR TITLE
Redmine 2.0.1

### PR DESCRIPTION
**Pull request by pedrosnk**
Hello,

First of all I wanted to thank you all for doing this amazing plugin and open it to the open source community, you guys are amazing <3.

So, I loved scrumbler, but I needed to use it on redmine-2.X so I take my time to adapt it to work on redmine. So I did the work and adapted somethings. Unfortunately the changes that needed to be done are not compatible with redmine.1.X. But I think would be awsome if you guys can put my changes into a separate branch and see if the community will help finish the job. I'm planing on doing more modifications into scrumbler, cause is not perfect wet. But is working, which I believe is a start.

U guys are awesome.

### CODE REVIEW

**Comment by invalidusrname** [comment]
I started working on porting to redmine 2 last night and made it to the router update, but looks like I won't have to continue the port. This is awesome and nice work! +1

**Comment by zloydadka** [comment]
pedrosnk, if you want i can make you collab of the repo

**Comment by pedrosnk** [comment]
That would be nice! :)

**Comment by zloydadka** [comment]
done

**Comment by xeta** [comment]
Great work!!!

**Pull request merged**
